In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [7]:
dst= pd.read_csv('DREAM7_DrugSensitivity1_Drug_Response_Training.txt', index_col=0, header=0, sep= "\t")
dst.index.name='cell_line'
dst.reset_index(inplace=True)
dst.head(5)

,cell_line,Drug1,Drug2,Drug3,Drug4,Drug5,Drug6,Drug7,Drug8,Drug9,...,Drug22,Drug23,Drug24,Drug25,Drug26,Drug27,Drug28,Drug29,Drug30,Drug31
0,HCC1954,4.833,5.032,3.777,NaN,6.223,NaN,4.176,7.196,4.478,...,4.951,4.804,2.724,NaN,5.478,NaN,4.523,2.520,6.351,6.169
1,AU565,5.255,5.256,4.378,NaN,6.164,NaN,6.836,7.381,4.478,...,5.332,4.478,2.724,4.883,5.478,4.478,4.176,2.851,6.567,6.336
2,HCC1937,5.012,4.996,4.461,NaN,6.164,NaN,6.889,6.721,4.000,...,5.198,4.478,2.724,NaN,5.478,NaN,3.876,2.564,6.959,6.439
3,CAMA1,4.717,4.851,4.394,6.983,6.164,4.903,4.851,6.947,4.000,...,5.301,4.176,2.724,NaN,5.478,NaN,3.876,2.791,6.554,6.353
4,T47DKBLUC,5.166,5.186,4.004,7.277,NaN,NaN,6.996,7.013,4.000,...,NaN,4.478,2.724,NaN,5.478,NaN,3.876,2.762,6.496,6.012

In [18]:
ge= pd.read_csv('DREAM7_DrugSensitivity1_GeneExpression.txt', index_col=0, header=0, sep="\t")
ge=ge.transpose()
ge.index.name='cell_line'
ge.head(5)

HGNC_ID,C9orf152,ELMO2,RPS11,CREB3L1,PNMA1,MMP2,C10orf90,ERCC5,ZHX3,GPR98,...,GRIP2,GOLGA8B,GPLD1,RAB8A,RXFP2,PIK3IP1,SNRPD2,SLC39A6,CTSC,AQP7
cell_line,,,,,,,,,,,,,,,,,,,,,
184B5,3.613030,7.205940,10.476276,5.565989,7.664038,5.108659,4.128089,7.263226,5.742329,3.671584,...,6.164306,4.648155,3.741650,8.103385,3.035962,5.094983,8.347877,9.560331,8.014001,5.611784
600MPE,8.463736,7.959597,9.939852,9.835957,7.645439,4.611590,3.687597,7.450175,5.199320,5.755408,...,5.716731,5.082299,3.848673,9.345093,3.042711,5.838762,8.134302,9.230374,5.489988,5.135123
AU565,7.935823,8.073369,9.817430,5.696639,7.761882,4.765150,3.883901,7.204121,5.477589,6.198794,...,6.133836,4.844242,4.605217,9.343916,2.862658,5.259975,8.465382,8.702158,6.926434,5.309263
BT20,3.098928,8.164778,10.038500,4.972852,7.766212,4.657057,3.848230,7.758748,5.764572,3.560379,...,5.777977,5.019017,3.948915,9.465953,2.781718,4.581164,8.861059,6.829949,6.706568,5.232824
BT474,9.010836,8.120015,9.533423,8.155372,8.393242,4.584473,3.667176,6.542780,4.882232,4.810989,...,5.780276,5.151477,4.066432,8.841824,2.879156,6.680903,8.264550,9.895278,4.959705,5.212809

In [20]:
ex= pd.read_csv('DREAM7_DrugSensitivity1_Exomeseq.txt', index_col=0, header=0, sep="\t")
ex.index.name='cell_line'
ex.head(5)

,Tissue,dbSNP,CancerGene?,#Cosmic,Type,HGNC_ID,Summary,Chromosome,Start,Stop,...,Zygosity(tumor),RefCount(tumor),AltCount(tumor),Avg#Mismatch(ref),Avg#Mismatch(alt),MismatchQualitySum(ref),MismatchQualitySum(alt),DistanceEffective3'end(ref),DistanceEffective3'end(alt),Details
cell_line,,,,,,,,,,,,,,,,,,,,,
184A1,Germline,.,No,0,Missense,TTLL10,p.G112R,1,1115548,1115548,...,het,66,53,0.273,0.396,3.606,4.075,0.282,0.285,TTLL10/uc001acy.2:Missense:p.G112R:TTLL10/uc01...
184A1,Germline,.,No,0,Missense,CPSF3L,p.T75I,1,1254635,1254635,...,het,24,46,0.542,0.761,4.333,4.196,0.547,0.423,CPSF3L/uc001aee.1:Intron:CPSF3L/uc001aef.1:Int...
184A1,Germline,.,No,0,Missense,CCNL2,p.R93P,1,1334409,1334409,...,het,6,29,0.333,1.345,0.500,3.966,0.550,0.246,CCNL2/uc001afi.2:Missense:p.R93P:CCNL2/uc001af...
184A1,Germline,.,No,0,Missense,ATAD3C,p.G337R,1,1398008,1398008,...,het,58,62,0.138,0.032,1.879,0.306,0.547,0.605,ATAD3C/uc001aft.2:Missense:p.G337R
184A1,Germline,.,No,0,Missense,ATAD3B,p.R579C,1,1430985,1430985,...,hom,0,327,0.000,0.257,0.000,2.813,0.000,0.469,ATAD3B/uc001afv.3:Missense:p.R579C:ATAD3B/uc00...

In [23]:
me= pd.read_csv('DREAM7_DrugSensitivity1_Methylation.txt', index_col=[0,1], header=0,sep="\t")
me=me.transpose()
me.index.name='cell_line'
me.head(5)

Illumina_ID,cg00000292,cg00002426,cg00003994,cg00005847,cg00006414,cg00007981,cg00008493,cg00008713,cg00009407,cg00010193,...,cg27653134,cg27654142,cg27655855,cg27655905,cg27657249,cg27657283,cg27661264,cg27662379,cg27662877,cg27665659
HGNC_ID,ATP2A1,SLMAP,MEOX2,HOXD3,ZNF398,PANX1,COX8C,IMPA2,TTC8,FLJ35816,...,A2ML1,ZFP2,CST9L,C11orf24,QPRT,LEPRE1,GNAS,RPN1,CYB5A,AP1S1
cell_line,,,,,,,,,,,,,,,,,,,,,
CGct1,2.000000,3.000000,1.000000,1.000000,4.000000,2.000000,4.000000,4.000000,4.000000,2.000000,...,1.000000,4.000000,1.000000,3.000000,1.000000,1.000000,3.000000,3.000000,4.000000,2.000000
Cct1,10.000000,10.000000,13.000000,12.000000,9.000000,9.000000,9.000000,9.000000,9.000000,12.000000,...,9.000000,10.000000,10.000000,10.000000,7.000000,14.000000,11.000000,16.000000,8.000000,12.000000
600MPE,0.881395,0.067202,0.863474,0.842265,0.084663,0.073098,0.961299,0.043818,0.035867,0.600882,...,0.777988,0.053180,0.859913,0.061986,0.184056,0.065804,0.428571,0.041231,0.056191,0.048137
AU565,0.625653,0.056657,0.038321,0.102223,0.091306,0.035754,0.938967,0.044103,0.020757,0.580747,...,0.192053,0.033415,0.586254,0.073783,0.085023,0.063036,0.522475,0.027320,0.044014,0.037855
BT20,0.922304,0.057735,0.541085,0.893619,0.065515,0.058254,0.947617,0.044273,0.035800,0.633720,...,0.065998,0.042322,0.834211,0.091103,0.122519,0.104707,0.800574,0.035291,0.113479,0.048670

In [24]:
rex= pd.read_csv('DREAM7_DrugSensitivity1_RNAseq_expressed_calls.txt', index_col=[0,1], header=0,sep="\t" )
rex=rex.transpose()
rex.index.name="cell_line"
rex.head(5)

HGNC_ID,TSPAN6,NFYA,ABCB4,EML1,ABCA9,ABCA6,ABCA10,ABCA5,ENPP3,C4orf19,...,ANGPT1,CYP4Z2P,PITPNC1,CC2D1B,LASS3,PRKCA,LRRK1,CCDC46,AC005332.1,GAL3ST2
Ensembl_ID,ENSG00000000003,ENSG00000001167,ENSG00000005471,ENSG00000066629,ENSG00000154258,ENSG00000154262,ENSG00000154263,ENSG00000154265,ENSG00000154269,ENSG00000154274,...,ENSG00000154188,ENSG00000154198,ENSG00000154217,ENSG00000154222,ENSG00000154227,ENSG00000154229,ENSG00000154237,ENSG00000154240,ENSG00000154251,ENSG00000154252
cell_line,,,,,,,,,,,,,,,,,,,,,
184A1,1,1,0,1,0,0,0,0,0,1,...,0,0,1,1,0,1,1,1,0,0
184B5,1,1,0,0,0,0,0,1,0,0,...,0,0,1,1,1,0,1,0,0,0
21MT1,1,1,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,1,0,0,0
21NT,1,1,0,0,0,0,0,0,0,0,...,0,0,1,1,0,1,1,0,0,0
600MPE,1,1,0,1,0,0,0,1,0,1,...,0,1,1,1,0,0,0,1,0,0

In [26]:
rqt= pd.read_csv('DREAM7_DrugSensitivity1_RNAseq_quantification.txt', index_col=[0,1], header=0,sep="\t" )
rqt=rqt.transpose()
rqt.index.name="cell_line"
rqt.head(5)

HGNC_ID,TSPAN6,NFYA,ABCB4,EML1,ABCA9,ABCA6,ABCA10,ABCA5,ENPP3,C4orf19,...,ANGPT1,CYP4Z2P,PITPNC1,CC2D1B,LASS3,PRKCA,LRRK1,CCDC46,AC005332.1,GAL3ST2
Ensembl_ID,ENSG00000000003,ENSG00000001167,ENSG00000005471,ENSG00000066629,ENSG00000154258,ENSG00000154262,ENSG00000154263,ENSG00000154265,ENSG00000154269,ENSG00000154274,...,ENSG00000154188,ENSG00000154198,ENSG00000154217,ENSG00000154222,ENSG00000154227,ENSG00000154229,ENSG00000154237,ENSG00000154240,ENSG00000154251,ENSG00000154252
cell_line,,,,,,,,,,,,,,,,,,,,,
184A1,95.212548,89.512619,0.000000,24.701397,0.000000,0.078395,0.754157,7.832908,0.000000,26.229312,...,0.095116,0.312106,48.382686,96.574779,0.490641,50.153014,51.372615,14.735200,12.728834,0.848276
184B5,95.698676,94.154375,0.172734,7.633869,2.683498,0.444747,2.676722,28.249303,0.447092,3.190776,...,8.347557,0.000000,45.562101,59.329639,39.597164,6.307886,19.782605,5.071096,11.363669,0.322965
21MT1,19.994674,245.433541,0.231762,5.842132,0.000000,0.000000,2.047496,0.618510,0.000000,0.449838,...,0.424730,0.000000,180.599546,77.862365,0.000000,73.198238,39.113584,1.690885,25.861896,3.354220
21NT,44.057746,286.092419,0.000000,5.149179,0.000000,0.000000,4.624529,1.536267,0.061169,0.559636,...,1.546384,0.222873,249.053343,82.658948,0.000000,91.826948,28.074873,1.303221,26.487033,1.464593
600MPE,178.158832,125.193255,0.757785,29.604076,0.652424,0.374778,1.405712,11.521642,4.779013,245.010683,...,0.000000,22.592765,29.157156,89.021735,0.000000,4.835407,4.591209,10.099978,73.157234,7.658614

In [28]:
rppa= pd.read_csv('DREAM7_DrugSensitivity1_RPPA.txt', index_col=[0,1], header=0,sep="\t" )
rppa=rppa.transpose()
rppa.index.name="cell_line"
rppa.head(5)

Antibody_ID,EIF4EBP1,EIF4EBP1-p37,EIF4EBP1-p65,NCOA3,"AKT1,AKT2,AKT3","AKT1-p308,AKT2-p308,AKT3-p308","AKT1-p473,AKT2-p473,AKT3-p473",PRKAA1,PRKAA1-p,CTNNB1,...,RBM15,ROPN1,YWHAB,YWHAZ,KIAA1324,HDAC7,TOP2A,EIF4EBP1-p70,SGK1,SGK-p
FullyValidated,Yes,Yes,No,No,Yes,Yes,Yes,No,Yes,Yes,...,No,No,No,No,Yes,No,No,No,No,No
cell_line,,,,,,,,,,,,,,,,,,,,,
184A1,-0.514511,-0.602368,-0.346251,0.025026,0.514092,-1.007596,0.375858,-0.859534,-0.448718,1.321012,...,-0.673984,0.429552,0.054774,0.327387,-0.262740,-0.883564,-0.857696,-0.114089,0.017733,-0.033872
184B5,0.865465,0.021478,-0.128969,0.268660,-0.041664,0.030733,1.386861,0.013433,0.014486,0.952219,...,-0.676641,-0.230129,0.551818,1.618936,0.618696,0.861536,-0.082255,-0.283775,-0.163854,-0.432831
600MPE,0.189235,-0.691073,-0.561238,-0.153393,0.648638,-0.994399,-2.063608,0.199899,-0.567515,1.222185,...,0.200365,0.866385,0.125099,-0.920038,-0.951176,1.075664,0.397551,-0.539791,0.102494,0.507750
AU565,-2.170981,-0.711503,-0.194758,0.064824,0.675827,0.109369,-0.809141,-0.602521,-0.741850,-3.916897,...,1.129522,0.756553,0.665532,-0.571059,1.226529,0.968145,1.388076,-1.393164,-0.006545,0.597923
BT20,-0.174487,0.050302,0.297102,0.621607,-1.710499,1.881318,1.972793,-0.014487,-1.019570,1.187255,...,0.460673,-0.379351,0.817023,-0.578621,-0.083213,0.590389,0.465760,0.392990,-0.182332,0.022890

In [30]:
dst_6= pd.read_csv('DREAM7_DrugSensitivity1_SNP6.cbs', index_col=[0], header=0,sep="\t")
dst_6.index.name="cell_line"
dst_6.head(5)

           Chromosome      Start       Stop  Count   Mean
cell_line
184B5               1      51599   72541087  44210 -0.046
184B5               1   72541505   72583737     46  1.675
184B5               1   72584492  110028494  24236 -0.027
184B5               1  110028841  110044477     24  1.090
184B5               1  110046522  143797135   7606 -0.050

In [32]:
dst_6g= pd.read_csv('DREAM7_DrugSensitivity1_SNP6_gene_level.txt', index_col=[0,1], header=0,sep="\t" )
dst_6g=dst_6g.transpose()
dst_6g.index.name="cell_line"
dst_6g.head(5)

EntrezID,403263,79501,645543,653340,643670,653341,643698,440550,653345,440551,...,375775,64975,92715,116225,92714,85026,79813,643210,774,643224
HGNC_ID,OR4G11P,OR4F5,LOC645543,LOC653340,LOC643670,LOC653341,LOC643698,LOC440550,LOC653345,LOC440551,...,C9orf111,MRPL41,C9orf112,ZMYND19,ARRDC1,C9orf37,EHMT1,LOC643210,CACNA1B,LOC643224
cell_line,,,,,,,,,,,,,,,,,,,,,
184B5,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,...,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046,-0.046
21MT1,0.270,0.270,0.270,0.270,0.270,0.270,0.270,0.270,0.270,0.270,...,-0.035,-0.035,-0.035,-0.035,-0.035,-0.035,-0.035,-0.035,-0.035,-0.035
21NT,0.112,0.112,0.112,0.112,0.112,0.112,0.112,0.112,0.112,0.112,...,-0.053,-0.053,-0.053,-0.053,-0.053,-0.053,-0.053,-0.053,-0.053,-0.053
600MPE,0.332,0.332,0.332,0.332,0.005,0.005,0.005,0.005,0.005,0.005,...,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003,0.003
AU565,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,-0.136,...,-0.163,-0.163,-0.163,-0.163,-0.163,-0.163,-0.163,-0.163,-0.163,-0.163